# Generated by Django 4.2.15 on 2024-10-09 05:42

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0018_auto_20230925_2243'),
        ('claim', '0030_merge_20240318_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='care_type',
            field=models.CharField(blank=True, db_column='CareType', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='inbound_referral_date',
            field=core.fields.DateField(blank=True, db_column='InboundReferralDate', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='patient_outcome',
            field=models.CharField(blank=True, db_column='PatientOutcome', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='refer_from',
            field=models.ForeignKey(blank=True, db_column='ReferFrom', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='referFromHF', to='location.healthfacility'),
        ),
        migrations.AddField(
            model_name='claim',
            name='refer_to',
            field=models.ForeignKey(blank=True, db_column='ReferTo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='referToHF', to='location.healthfacility'),
        ),
        migrations.AddField(
            model_name='claim',
            name='referral_id',
            field=models.IntegerField(blank=True, db_column='ReferralID', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='visit_reason',
            field=models.CharField(blank=True, db_column='VisitReason', max_length=500, null=True),
        ),
    ]
